apiVersion: v1
kind: Secret
metadata:
  name: dynamo-secret
type: kubernetes.io/basic-auth
stringData:
  amazon.aws.accesskey: AKIAVJ3PLDFF5WBJPGNJ
  amazon.aws.secretkey: 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
  username: user
  password: pass